version: '3.4'

services:
  simplestoreweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8888:80

  data:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pass@word
      - POSTGRES_DB=store
      - DATA=/data/postgres
    volumes:
      - /database-data:/var/lib/postgresql/data/
    ports:
        - "3333:5432"
