version: '3.4'

services:
  simplestoreweb:
    image: ${DOCKER_REGISTRY-}simplestoreweb
    build:
      context: .
      dockerfile: Dockerfile

  data:
     image: postgres:12.4

volumes:
  database-data:
